name: Download and Extract Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  download-and-extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download package with retries
      run: |
        URL1="http://example.com/path/to/package.tar.gz"
        URL2="http://backup.example.com/path/to/package.tar.gz"
        for i in {1..5}; do
          wget -O package.tar.gz $URL1 && break || sleep 15
          if [ $i -eq 5 ]; then
            wget -O package.tar.gz $URL2
          fi
        done

    - name: Extract package
      run: |
        mkdir -p extracted
        tar -xzvf package.tar.gz -C ./extracted

    - name: List contents
      run: ls -la ./extracted

    - name: Run script in extracted directory
      run: ./some-script.sh
      working-directory: ./extracted
