name: Setup Tomcat

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-tomcat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Tomcat
      run: wget -O tomcat.tar.gz https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz

    - name: Extract Tomcat
      run: |
        mkdir -p tomcat
        tar -xzvf tomcat.tar.gz -C ./tomcat --strip-components=1

    - name: List contents of Tomcat directory
      run: ls -la ./tomcat

    - name: Start Tomcat
      run: ./tomcat/bin/startup.sh
