name: Download and Extract Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  download-and-extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download package
      run: wget -O package.tar.gz http://example.com/path/to/package.tar.gz

    - name: Extract package
      run: tar -xzvf package.tar.gz -C ./extracted

    - name: List contents
      run: ls -la ./extracted

    - name: Run script in extracted directory
      run: ./extracted/some-script.sh
      working-directory: ./extracted
