name: Install Packages and Run Command

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update apt-get
      run: sudo apt-get update

    - name: Install packages
      run: |
        sudo apt-get install -y curl
        sudo apt-get install -y wget
        sudo apt-get install -y tree

    - name: Verify installation
      run: |
        curl --version
        wget --version
        tree --version

    - name: Run a command
      run: echo "Packages installed successfully!"
